name: Build and run tests

on:
  push:
    branches: [ main, prod, beta, staging, develop ]
  pull_request:
    branches: [ main, prod, beta, staging, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 10.16.3
        cache: 'npm'
    - run: npm i
    # - run: npm test

  deploy_develop:
    if: contains( github.ref, 'develop')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2 
    - name: Deploy in EC2
      env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        . ~/.nvm/nvm.sh &&
        echo "$PRIVATE_KEY" &&
        echo "$HOSTNAME" &&
        echo "$USER_NAME" &&
        cd /home/ubuntu/ootopia-stsrapi-develop &&
        git pull origin develop &&
        npm i &&
        npm run build &&
        pm2 delete ootopia-strapi-develop &&
        pm2 start npm --name "ootopia-strapi-develop" -- start
          '
  deploy_staging:
    if: contains( github.ref, 'staging')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2 
    - name: Deploy in EC2
      env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} uptime
        ssh -i private_key ${USER_NAME}@${HOSTNAME} '
        cd /home/ubuntu/ootopia-strapi-staging &&
        git pull origin staging &&
        npm i &&
        npm run build &&
        pm2 delete ootopia-strapi-staging &&
        pm2 start npm --name "ootopia-strapi-staging" -- start
          '
